# Generated by Django 5.2.1 on 2025-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_mapping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
