# Generated by Django 5.2.1 on 2025-06-01 08:32

from django.db import migrations

def load_sql_file(apps, schema_editor):
    sql_path = 'sql/school_db_dev_data.sql'
    with open(sql_path, 'r') as f:
        sql = f.read()
    schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ("data_mapping", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_sql_file),
    ]
