# Generated by Django 5.2.1 on 2025-05-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_mapping", "0002_alter_title_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="title",
            old_name="data_subject_type",
            new_name="data_subject_types",
        ),
    ]
