# Generated by Django 5.2.1 on 2025-05-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
