# Generated by Django 5.2.1 on 2025-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_permission_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                default="view_data_mapping", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
