# Generated by Django 5.2.1 on 2025-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_permission_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="authentication.role"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles", to="authentication.permission"
            ),
        ),
    ]
