# Generated by Django 5.2.1 on 2025-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_role_name_alter_role_parents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                related_name="users", to="authentication.role"
            ),
        ),
    ]
